
kind: pipeline
name: default
type: docker

steps:
  - name: push-to-gar
    image: plugins/gcr
    pull: never
    settings:
      tag: latest
      repo: ci-play/test/ml-service
      json_key:
        from_secret: gcr_json_key
